### ISSUE TITLE
How to read hub tilt sensor

### ISSUE THREAD

**Issue by ataribaby42** [nateswartz/boost-universal-windows-app#1]
Hello,
First thanks for this. Just found your project as I got Lego Boost Droid Commander set for kid and I wanted to try program it via c#. 

I was able to connect to Gonk droid and controls leds and motors with code like this:

var inter = controller.Hub.GetPortsByDeviceType(IOTypes.InternalMotor).ToList();
var ext = controller.Hub.GetPortsByDeviceType(IOTypes.ExternalMotor).ToList();
await controller.ExecuteCommandAsync(new MotorCommand(inter[2].PortID, 20, 5000, true));
await controller.ExecuteCommandAsync(new MotorCommand(ext[0].PortID, 20, 5000, true));

But I can't figure out how to get Hub Tilt sensor data. Can you please show me how to do it?

Thank you,
Ataribaby

**Comment by nateswartz** [comment]
There's a ToggleNotificationsCommand that can be used to receive data from the various sensors.  It works something like:
     
    static async Task Main(string[] args)
    {
        var adapter = new BluetoothLowEnergyAdapter(HandleDiscover, HandleConnect, HandleNotification, HandleDisconnect);
        ...
        var port = controller.GetPortIdsByDeviceType(IOTypes.TiltSensor).First();
        await controller.ExecuteCommandAsync(new ToggleNotificationsCommand(port, true, "01"));
        controller.AddEventHandler(new TiltToButtonEventHandler());
    }
    
    static async Task HandleNotification(IHubController controller, string message)
    {
        Console.WriteLine($"{controller.Hub.HubType}: {message}");
        await Task.CompletedTask;
    }

The two main mechanisms for using the sensor data is the HandleNotification callback you register with the BluetoothLowEnergyAdapter and an EventHandler.  The TiltToButtonEventHandler in the example doesn't exist, but you could create one following the pattern of the existing EventHandlers.

**Comment by ataribaby42** [comment]
Thanks for answer, perfect :)
Boost is great entry level before we will move to something like Mindstorm with kid and your project is exactly what I looked for.
